Update kotlintutorial.md
protocolbuffers/protocolbuffers.github.io pull request #60
Opened 2023-05-17 09:54 UTC by skulljoi

Fixing code, so it can work with kotlin

2023-05-26 18:38 UTC, Logofile commented
Thanks for the pull request! I've requested our Kotlin SWE to review the PR so that we can approve it.

2023-05-30 17:27 UTC, deannagarcia requested changes

2023-05-31 09:07 UTC, skulljoi commented on content/getting-started/kotlintutorial.md
> +    initialAddressBook.copy { people += promptPerson() }.writeTo(it)
I had a problem running the sample, so I asked chatgpt to help me fix it, so this was his recommendation.

2023-05-31 09:07 UTC, skulljoi commented on content/getting-started/kotlintutorial.md
> +    if (person.email.isNotEmpty()) {
I had a problem running the sample, so I asked chatgpt to help me fix it, so this was his recommendation.

2023-09-15 18:43 UTC, closed without merging